In [1]:
import pandas as pd
import numpy as np

In [2]:
EPIC_CSV_PATH = "../data/silver/epic_games_clean.csv"
STEAM_CSV_PATH = "../data/silver/steam_clean.csv"
IGDB_CSV_PATH = "../data/silver/igdb_clean_post.csv"

df_epic = pd.read_csv(EPIC_CSV_PATH)
df_steam = pd.read_csv(STEAM_CSV_PATH)
df_igdb = pd.read_csv(IGDB_CSV_PATH)

In [3]:
df_steam_pre2015 = pd.read_csv('../data/silver/steam_clean_pre2015.csv')
df_igdb_pre2015 = pd.read_csv('../data/silver/igdb_clean_pre2015.csv')
df_epic_pre2015 = pd.read_csv('../data/silver/epic-pre2015.csv')

In [4]:
df_epic["effective_date"] = pd.to_datetime(df_epic["effective_date"], errors="coerce")
df_steam["effective_date"] = pd.to_datetime(df_steam["effective_date"], errors="coerce")
df_igdb["release_date"] = pd.to_datetime(df_igdb["release_date"], errors="coerce")

In [5]:
def null_empty_percentage(df: pd.DataFrame):
    # Treat empty strings and whitespace-only strings as NaN
    df2 = df.replace(r'^\s*$', np.nan, regex=True)

    # Null % per column
    col_null_pct = (df2.isna().mean() * 100).round(2)

    # Average null rate across all columns
    avg_null_rate = col_null_pct.mean().round(2)

    return col_null_pct, avg_null_rate

In [7]:
print(dict(df_epic.dtypes.apply(lambda x: str(x))))

{'title': 'object', 'effective_date': 'datetime64[ns]', 'seller_name': 'object', 'tags_joined': 'object', 'original_price': 'float64', 'discount_price': 'float64', 'intermediate_price': 'float64', 'currency_code': 'object'}

In [8]:
print(dict(df_steam.dtypes.apply(lambda x: str(x))))

{'title': 'object', 'is_free': 'bool', 'developers': 'object', 'publishers': 'object', 'categories': 'object', 'genres': 'object', 'effective_date': 'datetime64[ns]', 'currency_code': 'object', 'discount_percent': 'float64', 'final_price': 'float64', 'final_price_usd': 'float64'}

In [9]:
print(dict(df_igdb.dtypes.apply(lambda x: str(x))))

{'name': 'object', 'genres': 'object', 'release_date': 'datetime64[ns]'}

In [ ]:
print(df_epic_pre2015.shape[0]) 
print(df_epic.shape[0])
print(df_steam_pre2015.shape[0])  
print(df_steam.shape[0]) 
print(df_igdb_pre2015.shape[0]) 
print(df_igdb.shape[0])

1736
6807
11946
74594
23620
132463

In [6]:
df_epic.describe()

,effective_date,original_price,discount_price,intermediate_price
count,6807,6805.000000,6805.000000,6805.000000
mean,2023-02-12 06:05:07.800793088,19.225571,15.968131,15.968131
min,2015-07-30 00:00:00,0.000000,0.000000,0.000000
25%,2021-10-05 12:00:00,4.990000,2.990000,2.990000
50%,2023-07-03 00:00:00,14.990000,9.990000,9.990000
75%,2024-08-16 00:00:00,24.990000,19.990000,19.990000
max,2025-12-01 00:00:00,199.990000,199.990000,199.990000
std,NaN,19.957692,19.043206,19.043206

In [7]:
df_epic.isnull().sum()

title                   0
effective_date          0
seller_name             0
tags_joined           156
original_price          2
discount_price          2
intermediate_price      2
currency_code           0
dtype: int64

In [8]:
print(null_empty_percentage(df_epic))

(title                 0.00
effective_date        0.00
seller_name           0.00
tags_joined           2.29
original_price        0.03
discount_price        0.03
intermediate_price    0.03
currency_code         0.00
dtype: float64, np.float64(0.3))

In [9]:
print(null_empty_percentage(df_epic_pre2015))

(title                  0.00
effective_date         0.00
seller_name            0.00
tags_joined           23.96
original_price        57.14
discount_price        57.14
intermediate_price    57.14
currency_code          0.00
dtype: float64, np.float64(24.42))

In [10]:
df_steam.describe()

,effective_date,discount_percent,final_price,final_price_usd
count,74594,64549.000000,64544.000000,64534.000000
mean,2021-03-08 14:30:27.557176320,4.319215,37.051003,11.076815
min,2015-01-01 00:00:00,0.000000,0.640000,0.460000
25%,2018-10-29 00:00:00,0.000000,3.390000,2.420000
50%,2021-06-10 00:00:00,0.000000,6.490000,4.630000
75%,2023-09-27 00:00:00,0.000000,12.990000,9.260000
max,2025-10-23 00:00:00,100.000000,759000.000000,8109.740000
std,NaN,16.377614,3939.389800,115.769623

In [11]:
df_steam.isnull().sum()

title                  16
is_free                 0
developers            145
publishers            448
categories            759
genres                110
effective_date          0
currency_code       10045
discount_percent    10045
final_price         10050
final_price_usd     10060
dtype: int64

In [12]:
print(null_empty_percentage(df_steam))

(title                0.02
is_free              0.00
developers           0.19
publishers           0.60
categories           1.02
genres               0.15
effective_date       0.00
currency_code       13.47
discount_percent    13.47
final_price         13.47
final_price_usd     13.49
dtype: float64, np.float64(5.08))

In [14]:
print(null_empty_percentage(df_steam_pre2015))

(name                64.26
is_free             65.59
developers          66.10
publishers          66.89
categories          65.94
genres              65.98
effective_date      68.88
currency_code       72.20
discount_percent    72.20
final_price         72.20
final_price_usd     72.33
dtype: float64, np.float64(68.42))

In [15]:
df_igdb.describe()

                        release_date
count                         132463
mean   2021-07-08 04:36:39.956214272
min              1970-12-31 00:00:00
25%              2019-02-16 00:00:00
50%              2022-01-28 00:00:00
75%              2024-04-16 00:00:00
max              2027-12-31 00:00:00

In [16]:
df_igdb.isnull().sum()

name               1
genres          8396
release_date       0
dtype: int64

In [17]:
print(null_empty_percentage(df_igdb))

(name            0.00
genres          6.34
release_date    0.00
dtype: float64, np.float64(2.11))

In [11]:
print(null_empty_percentage(df_igdb_pre2015))

(name            0.00
genres          7.95
release_date    0.00
dtype: float64, np.float64(2.65))