In [10]:
import pandas as pd
import ast

In [11]:
FINAL_CSV_PATH = "../data/gold/unified.csv"

final_df = pd.read_csv(FINAL_CSV_PATH)

In [12]:
print(dict(final_df.dtypes.apply(lambda x: str(x))))

{'Unnamed: 0': 'int64', 'id': 'int64', 'steam_ID': 'float64', 'epic_ID': 'object', 'igdb_ID': 'float64', 'title': 'object', 'platform': 'object', 'developers': 'object', 'publishers_steam': 'object', 'publishers_epic': 'object', 'categories_steam': 'object', 'categories_epic': 'object', 'categories_igdb': 'object', 'effective_date_steam': 'object', 'effective_date_epic': 'object', 'effective_date_igdb': 'object', 'price_steam': 'float64', 'price_epic': 'float64', 'discount_percent_steam': 'float64', 'discount_percent_epic': 'float64'}

In [13]:
def contains_indie(cat_list):
    if isinstance(cat_list, list):
        return any("indi" in str(x).lower() for x in cat_list)
    return False

def parse_list(x):
    if pd.isna(x):
        return []
    try:
        return ast.literal_eval(x)
    except:
        return []

In [14]:
for col in ["categories_steam", "categories_epic", "categories_igdb"]:
    final_df[col] = final_df[col].apply(parse_list)

final_df["is_indie"] = (
    final_df["categories_steam"].apply(contains_indie)
    | final_df["categories_epic"].apply(contains_indie)
    | final_df["categories_igdb"].apply(contains_indie)
)

indie_games = final_df[final_df["is_indie"]]

In [15]:
indie_games.head()

,Unnamed: 0,id,steam_ID,epic_ID,igdb_ID,title,platform,developers,publishers_steam,publishers_epic,...,categories_epic,categories_igdb,effective_date_steam,effective_date_epic,effective_date_igdb,price_steam,price_epic,discount_percent_steam,discount_percent_epic,is_indie
1,1,2,2556940.0,NaN,NaN,! shakabula *,['steam'],['Skermunkel'],['Skermunkel'],NaN,...,[],[],2023-10-13,NaN,NaN,13.88,NaN,0.0,NaN,True
2,2,3,449940.0,NaN,NaN,! that bastard is trying to steal our gold !,['steam'],['WTFOMGames'],['WTFOMGames'],NaN,...,[],[],2016-03-03,NaN,NaN,2.77,NaN,0.0,NaN,True
4,4,5,866510.0,NaN,NaN,!anyway!,['steam'],['EYEFRONT'],['EYEFRONT'],NaN,...,[],[],2018-06-06,NaN,NaN,1.84,NaN,0.0,NaN,True
5,5,6,NaN,NaN,103013.0,!dead pixels adventure!,['igdb'],NaN,NaN,NaN,...,[],"[Adventure, Indie]",NaN,NaN,2018-06-12,NaN,NaN,NaN,NaN,True
6,6,7,NaN,NaN,89658.0,!peace phantom 2!,['igdb'],NaN,NaN,NaN,...,[],"[Adventure, Indie]",NaN,NaN,2018-03-13,NaN,NaN,NaN,NaN,True

In [16]:
indie_games.describe()

,Unnamed: 0,id,steam_ID,igdb_ID,price_steam,price_epic,discount_percent_steam,discount_percent_epic
count,91916.000000,91916.000000,5.094600e+04,80851.000000,44745.000000,1727.000000,44751.000000,1697.000000
mean,75889.488424,75890.488424,1.563370e+06,194648.039554,8.536558,15.536804,4.347813,0.151796
std,43864.032574,43864.032574,8.816565e+05,103790.910798,67.566499,8.946123,16.448353,0.288807
min,1.000000,2.000000,1.690000e+04,1338.000000,0.460000,0.000000,0.000000,0.000000
25%,37732.500000,37733.500000,8.264900e+05,114573.500000,2.340000,9.990000,0.000000,0.000000
50%,75678.500000,75679.500000,1.388680e+06,188109.000000,4.620000,14.990000,0.000000,0.000000
75%,114126.250000,114127.250000,2.222702e+06,287353.500000,8.890000,19.990000,0.000000,0.000000
max,151208.000000,151209.000000,3.744990e+06,377798.000000,4604.450000,49.990000,100.000000,1.000000

In [18]:
indie_games = indie_games.drop(columns=['Unnamed: 0'], errors='ignore')
indie_games = indie_games.drop(columns=['is_indie'], errors='ignore')
indie_games.to_csv('../data/gold/indie.csv')

In [20]:
notindie_games = final_df[~final_df["is_indie"]]
notindie_games.head()

,Unnamed: 0,id,steam_ID,epic_ID,igdb_ID,title,platform,developers,publishers_steam,publishers_epic,...,categories_epic,categories_igdb,effective_date_steam,effective_date_epic,effective_date_igdb,price_steam,price_epic,discount_percent_steam,discount_percent_epic,is_indie
0,0,1,2299620.0,NaN,NaN,NaN,['steam'],['N/A'],['N/A'],NaN,...,[],[],2023-04-21,NaN,NaN,NaN,NaN,NaN,NaN,False
3,3,4,1287250.0,NaN,NaN,! wild russia !,['steam'],['Andreev Worlds'],['Andreev Worlds'],NaN,...,[],[],2020-04-28,NaN,NaN,16.23,NaN,0.0,NaN,False
7,7,8,439260.0,NaN,NaN,"""butts: the vr experience""",['steam'],['Gentle Manhands'],['Gentle Manhands'],NaN,...,[],[],2016-02-03,NaN,NaN,NaN,NaN,NaN,NaN,False
8,8,9,1377600.0,NaN,NaN,"""draw a card"" -simulator",['steam'],['StupidSimulators'],['Fireworks Productions'],NaN,...,[],[],2020-08-26,NaN,NaN,0.85,NaN,0.0,NaN,False
9,9,10,NaN,NaN,168659.0,"""draw a card"" simulator",['igdb'],NaN,NaN,NaN,...,[],[Simulator],NaN,NaN,2020-08-26,NaN,NaN,NaN,NaN,False

In [21]:
notindie_games.describe()

,Unnamed: 0,id,steam_ID,igdb_ID,price_steam,price_epic,discount_percent_steam,discount_percent_epic
count,59293.000000,59293.000000,1.954000e+04,49277.000000,16377.000000,4941.000000,16386.000000,4015.000000
mean,75161.435886,75162.435886,1.607257e+06,215370.619965,18.634520,20.424169,4.305016,0.172662
std,43313.852303,43313.852303,8.842160e+05,101047.303340,198.770201,22.596452,16.383975,0.303912
min,0.000000,1.000000,1.313000e+03,23.000000,0.460000,0.000000,0.000000,0.000000
25%,37953.000000,37954.000000,8.337850e+05,138798.000000,3.550000,3.990000,0.000000,0.000000
50%,75470.000000,75471.000000,1.495085e+06,226125.000000,7.470000,14.990000,0.000000,0.000000
75%,112659.000000,112660.000000,2.291362e+06,301336.000000,13.880000,29.990000,0.000000,0.300086
max,151201.000000,151202.000000,3.739090e+06,377779.000000,8058.650000,199.990000,95.000000,0.954774

In [22]:
notindie_games = notindie_games.drop(columns=['Unnamed: 0'], errors='ignore')
notindie_games = notindie_games.drop(columns=['is_indie'], errors='ignore')
notindie_games.to_csv('../data/gold/notindie.csv')